# Generated by Django 5.0.6 on 2024-06-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('isCompleted', models.BooleanField(default=False)),
            ],
        ),
    ]
